dataset:
  root: 'data/out.grib'
  pressure_level: 1000
  global_latitude: [45, -45]   # (a, b) in the range [90.0, 89.75, 89.5, ..., -89.5, -89.75, -90.0]
  global_longitude: [60, 150]   # (a, b) in the range [0.0, 0.25, 0.5, ..., 359.25, 359.5, 359.75]
  global_resolution: [128, 128]  # [x_res, y_res] or null to keep the original resolution
  local_latitude: [30, -10]
  local_longitude: [90, 130]
  train_fromyear: 1980
  train_toyear: 2022
  val_fromyear: 2023
  val_toyear: 2024
  indays: 10
  outdays: 3

global_architecture:
  embedding_dim: 1536
  n_layers: 12
  block_size: 384
  patch_size: [8, 8]
  dropout_rate: 0.
  from_checkpoint: null   # set to null to train from scratch

local_architecture:
  n_layers: 2
  block_size: 384
  patch_size: [7, 7]
  dropout_rate: 0.
  n_attention_heads: 8
  global_checkpoint: '.checkpoints/global/epoch55.pt'
  from_checkpoint: '.checkpoints/local/epoch20.pt'

training:
  noise_level: 0.
  train_batch_size: 4
  val_batch_size: 2
  learning_rate: 5e-4
  n_epochs: 1000
  patience: 50
  tolerance: 0.
  save_frequency: 1

predict:
  ondate: '20240906'
  from_global_checkpoint: '.checkpoints/global/epoch55.pt'
  from_local_checkpoint: '.checkpoints/local/epoch20.pt'
  global_plot_resolution: null   # set to null to respect the true resolution
  local_plot_resolution: null   # set to null to respect the true resolution


