dataset:
  # Training Paths
  train_gt: "../5.-Data_Split_train_val_test/CERRA/Split_data_2010-2022/ByYear/train_data_m_s_2010_2019_pen_CERRA.nc"
  train_mask: "../5.-Data_Split_train_val_test/CERRA/Split_data_2010-2022/ByYear/2010-2019/AEMET/mask_aemet_daily-wind_m_s_2010-2019_CERRA.nc"
  
  # Validation Paths
  val_gt: "../5.-Data_Split_train_val_test/CERRA/Split_data_2010-2022/ByYear/val_data_m_s_2020_2020_pen_CERRA.nc"
  val_mask: "../5.-Data_Split_train_val_test/CERRA/Split_data_2010-2022/ByYear/2020-2020/AEMET/mask_aemet_daily-wind_m_s_2020-2020_CERRA.nc"

  # inference Paths
  inf_gt: "../5.-Data_Split_train_val_test/CERRA/Split_data_2010-2022/ByYear/2021-2022/AEMET/aemet_daily-wind_m_s_2021-2022_CERRA.nc"
  inf_mask: "../5.-Data_Split_train_val_test/CERRA/Split_data_2010-2022/ByYear/2021-2022/AEMET/mask_aemet_daily-wind_m_s_2021-2022_CERRA.nc"

  # Variable Names (Leave null to auto-detect)
  gt_var: "ws"
  mask_var: "ws"

architecture:
  img_size: [250, 250]   
  # Model Hyperparameters
  embedding_dim: 64
  n_layers: 4
  block_size: 16
  patch_size: [25, 25]  # [height_patch, width_patch]
  global_downsample_factor: 2
  dropout_rate: 0.0
  
normalization:
  method: "z_score"         # Must match what you ran in Step 1
  stats_file: "data/stats.npz"
  
training:
  batch_size: 32
  learning_rate: 1.0e-4
  n_epochs: 300
  save_dir: "./checkpoints"
  save_frequency: 10 # Save model every X epochs

mlflow:
  experiment_name: "AdaptAFNO_Wind_Inpainting"
  run_name: "Run_Patch25_Embed256" # Optional: distinct name for this specific config
  tracking_uri: "mlruns"           # Directory where logs are saved