name: neural_operator
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - blosc=1.21.6=hef167b5_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.32.3=h4bc722e_0
  - ca-certificates=2024.7.4=hbcca054_0
  - freeglut=3.2.2=ha6d2627_3
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - icu=75.1=he02047a_0
  - jasper=4.2.4=h536e39c_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libaec=1.1.3=h59595ed_0
  - libcurl=8.9.1=hdb1bdb2_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=14.1.0=h77fa898_0
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libglu=9.0.0=ha6d2627_1004
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - libnetcdf=4.9.2=nompi_h80fb2b6_111
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcb=1.16=hd590300_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.3.1=h4ab18f5_1
  - llvm-openmp=18.1.8=hf5423f3_0
  - lz4-c=1.9.4=hcb278e6_0
  - ncurses=6.5=h59595ed_0
  - openssl=3.3.1=h4bc722e_2
  - pip=24.0=py310h06a4308_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.10.14=hd12c33a_0_cpython
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py310h06a4308_0
  - snappy=1.2.1=ha2e4443_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.43.0=py310h06a4308_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.4.6=h5eee18b_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - attrs==24.1.0
      - cads-api-client==1.2.0
      - cdsapi==0.7.0
      - certifi==2024.7.4
      - cffi==1.16.0
      - cfgrib==0.9.14.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - eccodes==1.7.1
      - filelock==3.15.4
      - findlibs==0.0.5
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - h5py==3.11.0
      - idna==3.7
      - jinja2==3.1.4
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - mpmath==1.3.0
      - multiurl==0.3.1
      - networkx==3.3
      - numpy==2.0.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - packaging==24.1
      - pandas==2.2.2
      - pillow==10.4.0
      - pycparser==2.22
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - requests==2.32.3
      - six==1.16.0
      - sympy==1.13.0
      - torch==2.3.1
      - torchvision==0.18.1
      - tqdm==4.66.5
      - triton==2.3.1
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - xarray==2024.7.0
prefix: /opt/conda/envs/neural_operator
