device: cuda

dataset:
  root: "data/2d/era5/wind"
  pressure_level: 1000
  global_latitude: [90, -90]   # (a, b) in the range [90.0, 89.75, 89.5, ..., -89.5, -89.75, -90.0]
  global_longitude: [0, 360]   # (a, b) in the range [0.0, 0.25, 0.5, ..., 359.25, 359.5, 359.75]
  global_resolution: [128, 128]  # [x_res, y_res] or null to keep the original resolution
  fromdate: '20240725'
  todate: '20240731'
  bundle_size: 12   # should match train_global
  window_size: 1    # should match train_global

architecture:
  global_checkpoint: ".checkpoints/global/1000/epoch270.pt"

plotting:
  plot_resolution: null # set to null to respect the global_resolution


