device: cuda

dataset:
  root: "data/2d/era5/wind"
  pressure_level: 1000
  fromdate: '20240101'
  todate: '20240731'
  global_latitude: [90, -90]   # (a, b) in the range [90.0, 89.75, 89.5, ..., -89.5, -89.75, -90.0]
  global_longitude: [0, 360]   # (a, b) in the range [0.0, 0.25, 0.5, ..., 359.25, 359.5, 359.75]
  global_resolution: [64, 64]
  local_latitude: [20, -20]
  local_longitude: [100, 120]
  local_resolution: [32, 32]
  split: [0.8, 0.2]

architecture:
  local_checkpoint: null   # set to null if train from scratch
  global_checkpoint: ".checkpoints/global/epoch29.pt"
  u_dim: 2
  depth: 4
  x_modes: 17
  y_modes: 17

training:
  lambda: 0.001
  noise_level: 0.01
  train_batch_size: 32
  val_batch_size: 4
  learning_rate: 0.001   # has no effect if architecture.local_checkpoint is given (not null)
  n_epochs: 100
  patience: 5
  tolerance: 0.
  checkpoint_path: "./.checkpoints/local"
  save_frequency: 5




