device: cuda

dataset:
  path: "data/2d/pdebench/diffreact/DiffReact2D.h5"
  input_timesteps: [0, 1, 2, 3, 4]
  target_timestep: 100
  resolution: [64, 64]  # [x_res, y_res] or null to keep the original resolution [128, 128]
  from_sample: 990  # must be in range 0-999
  to_sample: 999    # must be in range 0-999

architecture:
  from_checkpoint: ".checkpoints/arafno2d/epoch3.pt"
