device: cuda

dataset:
  path: "data/2D/diffusion-reaction/2D_diff-react_NA_NA.h5"
  window_size: 5
  resolution: [64, 64]  # (x_res, y_res) or null to keep the original resolution
  from_sample: 980
  to_sample: 1000

architecture:
  from_checkpoint: .checkpoints/epoch100.pt
