device: cuda

dataset:
  path: "data/2D/diffusion-reaction/2D_diff-react_NA_NA.h5"
  input_timesteps: [0, 1, 2, 3, 4]
  target_timestep: 100
  resolution: null  # (x_res, y_res) or null to keep the original resolution (128, 128)
  from_sample: 980  # must be in range 0-999
  to_sample: 999    # must be in range 0-999

architecture:
  from_checkpoint: .checkpoints/arafno2d/epoch5.pt
