device: cuda

dataset:
  root: 'data/era5'
  pressure_level: 1000
  global_latitude: [45, -45]   # (a, b) in the range [90.0, 89.75, 89.5, ..., -89.5, -89.75, -90.0]
  global_longitude: [60, 150]   # (a, b) in the range [0.0, 0.25, 0.5, ..., 359.25, 359.5, 359.75]
  global_resolution: [128, 128]  # [x_res, y_res] or null to keep the original resolution
  local_latitude: [30, -10]
  local_longitude: [90, 130]
  fromdate: '20230101'
  todate: '20240823'
  indays: 3
  outdays: 1

global_architecture:
  from_checkpoint: '.checkpoints/global/1000/epoch265.pt'   # should match train.yaml:/local_architecture.global_checkpoint

local_architecture:
  from_checkpoint: '.checkpoints/local/1000/epoch105.pt'

global_plotting:
  plot_resolution: null   # set to null to respect the global_resolution

local_plotting:
  plot_resolution: null   # set to null to respect the local_resolution


