device: cuda

dataset:
  root: "data/out.grib"
  pressure_level: 1000
  global_latitude: [45, -45]   # (a, b) in the range [90.0, 89.75, 89.5, ..., -89.5, -89.75, -90.0]
  global_longitude: [60, 150]   # (a, b) in the range [0.0, 0.25, 0.5, ..., 359.25, 359.5, 359.75]
  global_resolution: [128, 128]  # [x_res, y_res] or null to keep the original resolution
  local_latitude: [30, -10]
  local_longitude: [90, 130]
  # train_fromdate: '20000101'
  train_fromdate: '20201101'
  train_todate: '20201231'
  # val_fromdate: '20210101'
  val_fromdate: '20221215'
  val_todate: '20221231'
  indays: 3
  outdays: 1

global_architecture:
  embedding_dim: 1024
  n_layers: 4
  block_size: 128
  patch_size: [4, 4]
  dropout_rate: 0.1
  from_checkpoint: null   # set to null to train from scratch

local_architecture:
  block_size: 128
  patch_size: [4, 4]
  n_attention_heads: 8
  global_checkpoint: ".checkpoints/global/1000/epoch265.pt"
  from_checkpoint: null   # set to null to train from scratch

training:
  noise_level: 0.01
  train_batch_size: 4
  val_batch_size: 4
  learning_rate: 0.001   # has no effect if the according `from_checkpoint` is given (not null)
  n_epochs: 2
  patience: 50
  tolerance: 0.
  save_frequency: 5

