device: cuda

dataset:
  path: "data/2d/pdebench/diffreact/DiffReact2D.h5"
  window_size: 5
  resolution: [64, 64]  # [x_res, y_res] or null to keep the original resolution [128, 128]
  from_sample: 0    # must be in range 0-999
  to_sample: 989    # must be in range 0-999
  split: [0.8, 0.2]

architecture:
  u_dim: 2
  width: 256
  depth: 4
  x_modes: 33
  y_modes: 33
  from_checkpoint: null   # set to null if train from scratch

training:
  lambda: 0.
  train_batch_size: 32
  val_batch_size: 32
  learning_rate: 0.001   # has no effect if architecture.from_checkpoint is given (not null)
  n_epochs: 100
  patience: 5
  tolerance: 0.
  checkpoint_path: "./.checkpoints/arafno2d"
  save_frequency: 1


