device: cuda

dataset:
  path: "data/2D/diffusion-reaction/2D_diff-react_NA_NA.h5"
  window_size: 5
  resolution: [64, 64]  # [x_res, y_res] or null to keep the original resolution [128, 128]
  from_sample: 0    # must be in range 0-999
  to_sample: 979    # must be in range 0-999
  split: [0.8, 0.2]

architecture:
  u_dim: 2
  width: 256
  depth: 4
  x_modes: 33
  y_modes: 33
  from_checkpoint: .checkpoints/arafno2d/epoch2.pt

training:
  train_batch_size: 32
  val_batch_size: 32
  learning_rate: 0.0001   # has no effect if architecture.from_checkpoint is not null
  n_epochs: 100
  patience: 5
  tolerance: 1e-4
  checkpoint_path: "./.checkpoints/arafno2d"
  save_frequency: 1


